# 接続ユーザー(ansible_user)をsudo(管理者)グループに追加する
---
- name: "SSHユーザーをsudoグループに追加する({{ ansible_user }})"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: sudo
    append: true
  become: true
