# Clone the template in Proxmox and deploy it to each node.
# > ansible-playbook installation_all_vms.yml --ask-vault-pass -vv -e "tag=dev template_vmid=9000"
---
- name: Clone from the template and apply cloud-init/tags
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
    - ../vars/installation_all_vms_vars.yml
  module_defaults:
    ansible.builtin.uri: "{{ pve_uri_defaults }}"
  vars:
    tag: ""
    template_vmid: ""

  tasks:
    - name: Create the target VM
      ansible.builtin.include_tasks: tasks/installation_one_vm.yml
      loop: >-
        {{
          vms if tag == ''
          else vms | selectattr('tags', 'search', tag) | list
        }}
      loop_control:
        label: "{{ item.name }}"
