# このplaybookは既存VMの電源操作(起動/シャットダウン)を行います。
---
- name: 接続先のProxmoxホストを登録する
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../vault/proxmox.yml"

  tasks:
    - name: Proxmoxというグループでホストを追加
      ansible.builtin.import_role:
        name: proxmox_connect

- name: Proxmox VMの電源を操作する
  hosts: proxmox
  gather_facts: false

  roles:
    - proxmox_vm_powerctl
