---
- name: メモリサイズを引数に追加する
  ansible.builtin.set_fact:
    proxmox_vm_hardware_argv: "{{ proxmox_vm_hardware_argv + ['--memory', proxmox_vm_hardware_memory.size | string] }}"
  when: proxmox_vm_hardware_memory.size is defined

- name: バルーニング最小メモリを引数に追加する
  ansible.builtin.set_fact:
    proxmox_vm_hardware_argv: "{{ proxmox_vm_hardware_argv + ['--balloon', proxmox_vm_hardware_memory.balloon | string] }}"
  when: proxmox_vm_hardware_memory.balloon is defined
