---
- name: 設定するタイムゾーンを決定する
  ansible.builtin.set_fact:
    vm_timezone_resolved: "{{ vm_timezone | default('Asia/Tokyo', true) }}"

- name: "タイムゾーンを設定する({{ vm_timezone_resolved }})"
  community.general.timezone:
    name: "{{ vm_timezone_resolved }}"
  become: true
