---
- name: 設定するロケールを決定する
  ansible.builtin.set_fact:
    vm_locale_resolved: "{{ vm_locale | default('ja_JP.UTF-8', true) }}"

- name: "ロケールを生成する({{ vm_locale_resolved }})"
  community.general.locale_gen:
    name: "{{ vm_locale_resolved }}"
    state: present
  become: true

- name: デフォルトロケールを設定する
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: "LANG={{ vm_locale_resolved }}"
    create: true
    mode: "0644"
  become: true
