---
- name: テンプレートからVMを構築する
  ansible.builtin.command:
    cmd: >-
      qm clone {{ template_vmid }} {{ item.0 }}
      --name {{ item.1 }} --full
      --storage {{ target_storage }}
  register: proxmox_vm_build_clone_result
  changed_when: proxmox_vm_build_clone_result.rc == 0
  loop: "{{ proxmox_vm_build_vm_ids | zip(proxmox_vm_build_vm_names) | list }}"
  loop_control:
    label: "vm_id={{ item.0 }} vm_name={{ item.1 }}"
